<a href="https://colab.research.google.com/github/yongjaeahn/python_coding/blob/main/korean/source/07_%ED%8C%8C%EC%9D%BC_%EC%9E%85%EC%B6%9C%EB%A0%A5_%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

	파일 쓰기

In [ ]:
f = open('파일이름.txt','r')

FileNotFoundError: ignored

In [ ]:
try:
  print("try 블록은 예외가 발생할 것으로 예상되는 곳입니다.")
  result = True
except IndexError:
  print("except IndexError 블록은 인덱스가 허용한 범위를 벗어나는 예외가 발생할 때 실행됩니다.")
except ZeroDivisionError:
  print("except ZeroDivisionError 블록은 0으로 나누는 예외가 발생할 때 실행됩니다.")
except Exception as e:
  print("except 블록은 위의 두가지 이외의 예외가 발생할 때 실행됩니다.")
  print("예외 메세지 :",e)
else:
  print("try 블록에서 예외가 발생하지 않을 경우에만 else 블록이 실행됩니다.")
finally:
  print("finally 블록은 위의 블록들을 수행한 후 최종적으로 언제나 실행됩니다.")

try 블록은 예외가 발생할 것으로 예상되는 곳입니다.
try 블록에서 예외가 발생하지 않을 경우에만 else 블록이 실행됩니다.
finally 블록은 위의 블록들을 수행한 후 최종적으로 언제나 실행됩니다.


In [ ]:
try:
  print("try 블록은 예외가 발생할 것으로 예상되는 곳입니다.")
  list_variable = [1,2,3]
  result = list_variable[3]
except IndexError:
  print("except IndexError 블록은 인덱스가 허용한 범위를 벗어나는 예외가 발생할 때 실행됩니다.")
except ZeroDivisionError:
  print("except ZeroDivisionError 블록은 0으로 나누는 예외가 발생할 때 실행됩니다.")
except Exception as e:
  print("except 블록은 위의 두가지 이외의 예외가 발생할 때 실행됩니다.")
  print("예외 메세지 :",e)
else:
  print("try 블록에서 예외가 발생하지 않을 경우에만 else 블록이 실행됩니다.")
finally:
  print("finally 블록은 위의 블록들을 수행한 후 최종적으로 언제나 실행됩니다.")

try 블록은 예외가 발생할 것으로 예상되는 곳입니다.
except IndexError 블록은 인덱스가 허용한 범위를 벗어나는 예외가 발생할 때 실행됩니다.
finally 블록은 위의 블록들을 수행한 후 최종적으로 언제나 실행됩니다.


In [5]:
try:
  print("try 블록은 예외가 발생할 것으로 예상되는 곳입니다.")
  result = 1 / 0
except IndexError:
  print("except IndexError 블록은 인덱스가 허용한 범위를 벗어나는 예외가 발생할 때 실행됩니다.")
except ZeroDivisionError:
  print("except ZeroDivisionError 블록은 0으로 나누는 예외가 발생할 때 실행됩니다.")
except Exception as e:
  print("except 블록은 위의 두가지 이외의 예외가 발생할 때 실행됩니다.")
  print("예외 메세지 :",e)
else:
  print("try 블록에서 예외가 발생하지 않을 경우에만 else 블록이 실행됩니다.")
finally:
  print("finally 블록은 위의 블록들을 수행한 후 최종적으로 언제나 실행됩니다.")

try 블록은 예외가 발생할 것으로 예상되는 곳입니다.
except ZeroDivisionError 블록은 0으로 나누는 예외가 발생할 때 실행됩니다.
finally 블록은 위의 블록들을 수행한 후 최종적으로 언제나 실행됩니다.


In [ ]:
try:
  print("try 블록은 예외가 발생할 것으로 예상되는 곳입니다.")
  result = int("문자열")
except IndexError:
  print("except IndexError 블록은 인덱스가 허용한 범위를 벗어나는 예외가 발생할 때 실행됩니다.")
except ZeroDivisionError:
  print("except ZeroDivisionError 블록은 0으로 나누는 예외가 발생할 때 실행됩니다.")
except Exception as e:
  print("except 블록은 위의 두가지 이외의 예외가 발생할 때 실행됩니다.")
  print("예외 메세지 :",e)
else:
  print("try 블록에서 예외가 발생하지 않을 경우에만 else 블록이 실행됩니다.")
finally:
  print("finally 블록은 위의 블록들을 수행한 후 최종적으로 언제나 실행됩니다.")

try 블록은 예외가 발생할 것으로 예상되는 곳입니다.
except 블록은 위의 두가지 이외의 예외가 발생할 때 실행됩니다.
예외 메세지 : invalid literal for int() with base 10: '문자열'
finally 블록은 위의 블록들을 수행한 후 최종적으로 언제나 실행됩니다.


In [ ]:
try:
  f = open('파일이름.txt','r')
except FileNotFoundError:
  print("파일이름.txt 파일이 존재하지 않습니다.")
  print("파일 쓰기 프로그램을 먼저 실행한 후 읽기 작업을 하기 바랍니다.")

파일이름.txt 파일이 존재하지 않습니다.
파일 쓰기 프로그램을 먼저 실행한 후 읽기 작업을 하기 바랍니다.


In [ ]:
import math

def devide(number,divisor):
  try:
    return number / divisor
  except ZeroDivisionError:
    if number < 0: return -math.inf
    elif number == 0: return math.nan
    else: return math.inf

print('10 / 3 :',devide(10,3))
print('-1 / 0 :',devide(-1,0))
print('0 / 0 :',devide(0,0))
print('1 / 0 :',devide(1,0))

10 / 3 : 3.3333333333333335
-1 / 0 : -inf
0 / 0 : nan
1 / 0 : inf


In [ ]:
f = open('파일이름.txt','w')

In [ ]:
f.write('첫번째줄\n')
f.write('두번째줄\n')
f.write('세번째줄\n')

5

In [ ]:
f.close()

In [ ]:
try:
    f = open('파일이름.txt','w')
except IOError as e:
    print("파일 열기 오류 :",e)
    print("편집 중인 파일이름.txt 파일을 닫고 프로그램을 다시 실행하세요.")
else:
    f.write('첫번째줄\n')
    f.write('두번째줄\n')
    f.write('세번째줄\n')

    f.close()

In [ ]:
while True:
    try:
        f = open('파일이름.txt','w')
    except IOError as e:
        print("파일 열기 오류 :",e)
        input("편집 중인 파일이름.txt 파일을 닫고 Enter 키를 치세요.")
    else:
        f.write('첫번째줄\n')
        f.write('두번째줄\n')
        f.write('세번째줄\n')

        f.close()

        break

print("파일이름.txt 파일의 쓰기 작업이 완료되었습니다.")

In [ ]:
try:
    f = open('파일이름.txt','w')
except IOError as e:
    print("파일 열기 오류 :",e)
    print("편집 중인 파일이름.txt 파일을 닫고 프로그램을 다시 실행하세요.")
else:
    try:
        f.write('첫번째줄\n')
        f.write('두번째줄\n')
        f.write('세번째줄\n')
    except Exception as e:
        print("파일 출력 오류 :",e)
        print("파일이름.txt에 쓰기 작업을 하던 중 오류가 발생했습니다. 시스템 관리자에게 문의하세요.")
    finally:
        f.close()

	파일 내용 추가하기

In [ ]:
f = open('파일이름.txt','a')

f.write('네번째줄\n')
f.write('다섯번째줄\n')

f.close()

	파일 읽기

In [ ]:
f = open('파일이름.txt','r')

text_data = f.read()

f.close()

print(text_data)
print(repr(text_data))

첫번째줄
두번째줄
세번째줄
네번째줄
다섯번째줄

'첫번째줄\n두번째줄\n세번째줄\n네번째줄\n다섯번째줄\n'


In [ ]:
f = open('파일이름.txt','r')

text_data = f.readline()

f.close()

print(text_data)
print(repr(text_data))

첫번째줄

'첫번째줄\n'


In [ ]:
f = open('파일이름.txt','r')

while line := f.readline():
  print(repr(line))

f.close()

'첫번째줄\n'
'두번째줄\n'
'세번째줄\n'
'네번째줄\n'
'다섯번째줄\n'


In [ ]:
f = open('파일이름.txt','r')

while line := f.readline().rstrip():
  print(repr(line))

f.close()

'첫번째줄'
'두번째줄'
'세번째줄'
'네번째줄'
'다섯번째줄'


In [ ]:
f = open('/content/파일이름.txt','r')

while line := f.readline().rstrip():
  print(line)

f.close()

첫번째줄
두번째줄
세번째줄
네번째줄
다섯번째줄


In [ ]:
f = open('C:\\Users\\00320811\\Documents\\python_coding\\파일이름.txt','r')

while line := f.readline().rstrip():
    print(line)

f.close()

In [ ]:
f = open('C:/Users/00320811/Documents/python_coding/파일이름.txt','r')

while line := f.readline().rstrip():
    print(line)

f.close()

In [ ]:
f = open('파일이름.txt','r')

for line in f:
  print(line.rstrip())

f.close()

첫번째줄
두번째줄
세번째줄
네번째줄
다섯번째줄


In [ ]:
with open('파일이름.txt','w') as f:
  f.write('첫번째줄\n')
  f.write('두번째줄\n')
  f.write('세번째줄\n')

with open('파일이름.txt','r') as f:
  for line in f:
    print(line.rstrip())

첫번째줄
두번째줄
세번째줄


	파일 인코딩

In [ ]:
bin(ord('a'))   # 문자 'a'의 UTF-8 이진 코드
bin(ord('5'))   # 문자 '5'의 UTF-8 이진 코드
bin(5)          # 숫자 5의 UTF-8 이진 코드
bin(ord('안'))  # 한글 '안'의 UTF-8 이진 코드

In [ ]:
with open('파일이름.txt','r', encoding='utf-8') as f:
  in_list1d_str = f.readlines()

print(in_list1d_str)

['첫번째줄\n', '두번째줄\n', '세번째줄\n']


In [ ]:
with open('파일이름.txt','r', encoding='utf-8') as f:
    in_list1d_str = f.readlines()

print(in_list1d_str)

In [ ]:
with open('파일이름.txt','r', encoding='ansi') as f:
    in_list1d_str = f.readlines()

print(in_list1d_str)

In [ ]:
with open('파일이름.txt','w', encoding='utf-8') as f:
    f.write('첫번째줄\n')
    f.write('두번째줄\n')
    f.write('세번째줄\n')

with open('파일이름.txt','r', encoding='utf-8') as f:
    in_list1d_str = f.readlines()

print(in_list1d_str)

	리스트 입출력

In [ ]:
out_list_values = ['첫번째줄','두번째줄','세번째줄']

with open('파일이름.txt','w',encoding='utf-8') as f:
    f.writelines(out_list_values)

In [ ]:
with open('파일이름.txt','r',encoding='utf-8') as f:
  in_list_values = f.readlines()

print(in_list_values)

['첫번째줄두번째줄세번째줄']


In [ ]:
out_list_values = ['첫번째줄\n','두번째줄\n','세번째줄\n']

with open('파일이름.txt','w',encoding='utf-8') as f:
  f.writelines(out_list_values)

with open('파일이름.txt','r',encoding='utf-8') as f:
  in_list_values = f.readlines()

print(in_list_values)

['첫번째줄\n', '두번째줄\n', '세번째줄\n']


In [ ]:
out_int_values = [10,20,30,40,50]

with open('파일이름.txt','w',encoding='utf-8') as f:
  f.writelines(out_int_values)

TypeError: ignored

In [ ]:
out_int_values = [10,20,30,40,50]
out_string_values = [str(elem) for elem in out_int_values]
formatted_out_string = '\n'.join(out_string_values)

print('Formatted Out String :',repr(formatted_out_string))

with open('파일이름.txt','w',encoding='utf-8') as f:
  f.write(formatted_out_string)

with open('파일이름.txt','r',encoding='utf-8') as f:
  in_string_values = f.readlines()

print('In String Values :',in_string_values)
in_int_values = [int(value) for value in in_string_values]
print('In Integer Values :',in_int_values)

Formatted Out String : '10\n20\n30\n40\n50'
In String Values : ['10\n', '20\n', '30\n', '40\n', '50']
In Integer Values : [10, 20, 30, 40, 50]


In [ ]:
out_list2d_int = [[10,20,30,40,50],[60,70,80,90,100]]

out_list2d_str = [[str(elem) for elem in sublist1d] for sublist1d in out_list2d_int]

formatted_out_string_list = [','.join(sublist1d)+'\n' for sublist1d in out_list2d_str]

print('Out String Values :',out_list2d_str)
print('Formatted Out String :',formatted_out_string_list)

with open('파일이름.csv','w',encoding='utf-8') as f:
  f.writelines(formatted_out_string_list)

with open('파일이름.csv','r',encoding='utf-8') as f:
  inList1dStr = f.readlines()

print('In String Values 1d :',inList1dStr)
in_list2d_string = [elem.split(',') for elem in inList1dStr]
print('In Integer Values 2d :',in_list2d_string)
in_list2d_int = [[int(elem) for elem in sublist1d] for sublist1d in in_list2d_string]
print('In Integer Values :',in_list2d_int)

Out String Values : [['10', '20', '30', '40', '50'], ['60', '70', '80', '90', '100']]
Formatted Out String : ['10,20,30,40,50\n', '60,70,80,90,100\n']
In String Values 1d : ['10,20,30,40,50\n', '60,70,80,90,100\n']
In Integer Values 2d : [['10', '20', '30', '40', '50\n'], ['60', '70', '80', '90', '100\n']]
In Integer Values : [[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]]


In [ ]:
out_list2d_int = [[10,20,30,40,50],[60,70,80,90,100]]

out_list2d_str = []
for i,sublist1d in enumerate(out_list2d_int):
  out_list2d_str.append([])
  for elem in sublist1d:
    out_list2d_str[i].append(str(elem))

print('Out Integer Values :',out_list2d_str)

Out Integer Values : [['10', '20', '30', '40', '50'], ['60', '70', '80', '90', '100']]


	numpy 배열 입출력

In [ ]:
import numpy as np

out_array_matrix = np.arange(1,51).reshape(5,10)
print("out_array_matrix :\n",out_array_matrix)

np.savetxt("numpy배열.csv",out_array_matrix,fmt='%d',delimiter=',',encoding='utf-8')

in_array_matrix = np.loadtxt("numpy배열.csv",dtype='int',delimiter=",",encoding='utf-8')

print("in_array_matrix :\n",in_array_matrix)

out_array_matrix :
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
in_array_matrix :
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [ ]:
out_list2d_int = [[10,20,30,40,50],[60,70,80,90,100]]

with open('파일이름.csv','w',encoding='utf-8') as f:
  for sublist1d in out_list2d_int:
    out_list1d_str = [str(elem) for elem in sublist1d]
    print('Out String Values :',out_list1d_str)
    formatted_out_string = ','.join(out_list1d_str)+'\n'
    print('Formatted Out String :',repr(formatted_out_string))
    f.write(formatted_out_string)
print()
in_list2d_int = []
with open('파일이름.csv','r',encoding='utf-8') as f:
  while in_string := f.readline():
    print('In String Values :',repr(in_string))
    in_sublist1d = in_string.split(',')
    print('In Integer Values :',in_sublist1d)
    in_list2d_int.append([int(elem) for elem in in_sublist1d])
print('In Integer Values :',in_list2d_int)

Out String Values : ['10', '20', '30', '40', '50']
Formatted Out String : '10,20,30,40,50\n'
Out String Values : ['60', '70', '80', '90', '100']
Formatted Out String : '60,70,80,90,100\n'

In String Values : '10,20,30,40,50\n'
In Integer Values : ['10', '20', '30', '40', '50\n']
In String Values : '60,70,80,90,100\n'
In Integer Values : ['60', '70', '80', '90', '100\n']
In Integer Values : [[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]]


In [ ]:
def whole_data_io():
  out_list2d_int = [[10,20,30,40,50],[60,70,80,90,100]]
  out_list2d_str = [[str(elem) for elem in sublist1d] for sublist1d in out_list2d_int]
  formatted_out_string_list = [','.join(sublist1d)+'\n' for sublist1d in out_list2d_str]

  with open('파일이름.csv','w',encoding='utf-8') as f:
    f.writelines(formatted_out_string_list)

  with open('파일이름.csv','r',encoding='utf-8') as f:
    in_list1d_str = f.readlines()

  in_list2d_string = [elem.split(',') for elem in in_list1d_str]
  in_list2d_int = [[int(elem) for elem in sublist1d] for sublist1d in in_list2d_string]

def each_line_io():
  out_list2d_int = [[10,20,30,40,50],[60,70,80,90,100]]

  with open('파일이름.csv','w',encoding='utf-8') as f:
    for sublist1d in out_list2d_int:
      out_list1d_str = [str(elem) for elem in sublist1d]
      formatted_out_string = ','.join(out_list1d_str)+'\n'
      f.write(formatted_out_string)

  in_list2d_int = []
  with open('파일이름.csv','r',encoding='utf-8') as f:
    while in_string := f.readline():
      in_sublist1d = in_string.split(',')
      in_list2d_int.append([int(elem) for elem in in_sublist1d])

In [ ]:
import time

start = time.time()
whole_data_io()
end = time.time()

print(f'whole_data_io() 수행 시간\t: {end - start:.3f}초')

start = time.time()
each_line_io()
end = time.time()

print(f'each_line_io() 수행 시간\t: {end - start:.3f}초')

whole_data_io() 수행 시간	: 0.001초
each_line_io() 수행 시간	: 0.002초


In [ ]:
!pip install memory_profiler

In [ ]:
from memory_profiler import memory_usage

memory_usage_whole = memory_usage(whole_data_io)
print(f"whole_data_io() 메모리 사용량\t: {max(memory_usage_whole) - min(memory_usage_whole)}MB")

memory_usage_each = memory_usage(each_line_io)
print(f"each_line_io() 메모리 사용량\t: {max(memory_usage_each) - min(memory_usage_each)}MB")

whole_data_io() 메모리 사용량	: 0.00390625MB
each_line_io() 메모리 사용량	: 0.0MB


In [ ]:
import numpy as np

out_array_matrix = np.arange(1,51).reshape(5,10)

np.save("numpy배열.npy",out_array_matrix)

in_array_matrix = np.load("numpy배열.npy")

print("in_array_matrix :\n",in_array_matrix)
type(in_array_matrix)

in_array_matrix :
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


numpy.ndarray

In [ ]:
import numpy as np

out_array_matrix01 = np.arange(1,51).reshape(5,10)
out_array_matrix02 = np.arange(51,101).reshape(5,10)

np.savez("numpy배열들.npz",array01=out_array_matrix01,array02=out_array_matrix02)

in_array_matrix = np.load("numpy배열들.npz")

print("in_array_matrix['array01'] :\n",in_array_matrix['array01'])
print("in_array_matrix['array02'] :\n",in_array_matrix['array02'])
in_array_matrix.close()
type(in_array_matrix)

in_array_matrix['array01'] :
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
in_array_matrix['array02'] :
 [[ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


numpy.lib.npyio.NpzFile

In [ ]:
import numpy as np

out_array_matrix = np.arange(1,50001)

np.savetxt("대용량numpy배열.csv",out_array_matrix,fmt='%d',delimiter=',',encoding='utf-8')
np.save("대용량numpy배열.npy",out_array_matrix)
np.savez("대용량numpy배열.npz",array01=out_array_matrix)
np.savez_compressed("대용량numpy배열-압축.npz",array01=out_array_matrix)

In [ ]:
import numpy as np
import time

out_array_matrix = np.arange(1,50001)

start = time.time()
np.savetxt("대용량numpy배열.csv",out_array_matrix,fmt='%d',delimiter=',',encoding='utf-8')
end = time.time()
print(f'csv 파일 저장 시간\t: {end - start:.3f}초')

start = time.time()
np.save("대용량numpy배열.npy",out_array_matrix)
end = time.time()
print(f'바이너리 파일 저장 시간\t: {end - start:.3f}초')

start = time.time()
np.savez_compressed("대용량numpy배열-압축.npz",array01=out_array_matrix)
end = time.time()
print(f'압축 바이너리 파일 저장 시간\t: {end - start:.3f}초')

	모니터링 로그 쓰기

In [ ]:
import logging

logging.basicConfig(filename='monitoring.log',
                    encoding='utf-8',
                    format='%(asctime)s %(levelname)s %(message)s',
                    level=logging.INFO)

memory_usage = 10
logging.debug(f'메모리 사용량 : {memory_usage}MB')
logging.info('프로그램이 기동되었습니다.')
logging.info(repr('\t\n과 같은 특수 문자가 포함된 로그의 출력은 repr() 함수를 사용합니다.'))
logging.warning('나눗셈에 사용될 out_array_matrix 배열에 0이 포함되어 있습니다.')
logging.error('나눗셈에 사용될 divisor 변수의 값이 0입니다.')
logging.critical('프로그램이 정상 종료되지 않았습니다.')
logging.info('프로그램이 종료되었습니다.')

In [ ]:
import logging

logging.basicConfig(filename='monitoring.log',
                    encoding='utf-8',
                    format='%(asctime)s %(levelname)s %(message)s',
                    #level=logging.INFO)
                    level=logging.DEBUG)

memory_usage = 10
logging.debug(f'메모리 사용량 : {memory_usage}MB')
logging.info('프로그램이 기동되었습니다.')
logging.info(repr('\t\n과 같은 특수 문자가 포함된 로그의 출력은 repr() 함수를 사용합니다.'))
logging.warning('나눗셈에 사용될 out_array_matrix 배열에 0이 포함되어 있습니다.')
logging.error('나눗셈에 사용될 divisor 변수의 값이 0입니다.')
logging.critical('프로그램이 정상 종료되지 않았습니다.')
logging.info('프로그램이 종료되었습니다.')

In [ ]:
import logging

logging.basicConfig(filename='monitoring.log',
                    encoding='utf-8',
                    format='%(asctime)s %(levelname)s %(message)s',
                    #level=logging.INFO)
                    level=logging.DEBUG)

try:
    result = 10 / 0
except Exception:
    logging.exception('처리할 수 없는 예외가 발생하여 프로그램의 실행을 종료합니다.')